[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["zod"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
